### PR TITLE
Fix #151, don't remove tokens before body for Function0

### LINKED ISSUE #151: Regression with anon functions as parameters to macro annotations
Using the macro below...

```scala
@compileTimeOnly("@before not expanded")
class before(fun: () => Unit) extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"new $_(() => ${apply: Term.Apply})" = this
    defn
}
```

The below compiles in 3.0.0-M5
but does not in 3.0.0-beta4

Both using scalameta 1.4.0

```scala
@before(() => print("hello"))
def world(): Unit = println(" world")
```

It appears the `() =>` part of the tree has disappeared....

Replacing with:

```scala
@compileTimeOnly("@before not expanded")
class before(fun: () => Unit) extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"new $_(${apply: Term.Apply})" = this // Note this line has changed
    defn
}
```

Successfully compiles.

Surely this is a regression? you should actually have to specify the anon function syntax rather then just having a statement.

### PR DESCRIPTION
**Pull request by shadaj**
This is needed for Slinky (https://github.com/shadaj/slinky), where Function0's in the body of macro annotated classes are very common.

### CODE REVIEW

**Comment by DavidDudson** [comment]
I wonder if this fixes a big I encountered where Function0’s were having the tokens before body when passed in as parameters to macros.

**Comment by DavidDudson** [comment]
Never mind. I just saw the bug number mentioned.

**Comment by shadaj** [comment]
Thanks for the quick review @DavidDudson! Would it be possible for this change to be included in a release? A snapshot would work fine too.

**Comment by olafurpg** [comment]
Thank you for this fix @shadaj ! It seems our drone CI stopped working, I opened #236 to setup Travis and release on tag push so we can easily cut releases :) If you watch the repo you should get a notification once the release is out.

**Comment by olafurpg** [comment]
The tests seems to be flaky when running for both 2.11/2.12 in the same sbt session so I manually published 3.0.0-M11

File: plugin/src/main/scala/org/scalameta/paradise/converters/LogicalTrees.scala [hunk 1]
```diff
@@ -123,7 +123,7 @@ class LogicalTrees[G <: Global](val global: G, root: G#Tree) extends ReflectTool
         // before: function((x$1, x$2) => x$1 + x$2)
         // after:  function(_ + _)
         case g.Function(vparams, body)
-            if vparams.forall(x =>
+            if vparams.nonEmpty && vparams.forall(x =>
```
Comment (marconilanna) [inline plugin/src/main/scala/org/scalameta/paradise/converters/LogicalTrees.scala]: Isn't this equivalent to `exists`?

Comment (shadaj) [reply plugin/src/main/scala/org/scalameta/paradise/converters/LogicalTrees.scala]: @marconilanna `exists` would pass even if only one of the params was synthetic, but here we want to make sure that all the params are synthetic with the edge case where there are no parameters at all (since `forall` by itself would return `true`)
